<?php
/**
 * Created by PhpStorm.
 * User: 李佳飞
 * Date: 2017/12/14 0014
 * Time: 16:02
 * 后台管理员为每个小程序设置分销，设置分销的只有小程序有支付的时候，才能启用分销
 */
namespace app\custom\controller;

class Distribution extends Action{
    
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input('post.','','htmlspecialchars');
        if(!isset($this->data['appid'])){
            $return['code'] = 10100;
            $return['msg_test'] = 'appid参数值缺失';
            echo json_encode($return);exit;
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10200;
            $return['msg_test'] = 'appid格式不正确';
            echo json_encode($return);exit;
        }
        $custom_id = db('app') -> where(['appid' => $this->data['appid']]) -> value('custom_id');
        if($custom_id != $this->custom->id){
            $return['code'] = 10300;
            $return['msg_test'] = '当前app不是这个用户的';
            echo json_encode($return);exit;
        }
    }
    //分销详情
    public function getDistInfo() {
        $info = db('dist_rule') -> where(['appid' => $this->data['appid']]) -> find();
        if ($info) {
            $return['code'] = 10000;
            $return['msg_test'] = '查询成功';
            $return['data'] = $info;
            return json($return);
        } else {
            $return['code'] = 10001;
            $return['msg_test'] = '查询失败,请稍后重试';
            return json($return);
        }
        
    }
    //分销设置
    public function setDist() {
        if (!isset($this->data['switch'])) {
            $return['code'] = 10001;
            $return['msg_test'] =  'switch不存在';
            return  json($return);
        }
        $res = model('dist_rule')->allowField(true)->save($this->data);
        if ($res) {
            $return['code'] = 10000;
            $return['msg_test'] = '保存成功';
            return json($return);
        } else {
            $return['code'] = 10002;
            $return['msg_test'] = '网络错误';
        }
    }
    
}