<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/30 0030
 * Time: 09:13
 * 关于轮播图的接口都在这里定义
 * 主题色  商品布局 搜索功能 在线客服
 */
namespace app\custom\controller;
class Loop extends Action{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input("post.",'','htmlspecialchars');
        if(!isset($this->data['appid'])){
            $return['code'] = 10001;
            $return['msg_test'] = '参数值缺失';
            echo json_encode($return);exit;
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10002;
            $return['msg_test'] = 'appid格式不正确';
            echo json_encode($return);exit;
        }
        $custom_id = db('app') -> where("appid",$this->data['appid']) -> value('custom_id');
        if($custom_id != $this->custom->id){
            $return['code'] = 100020;
            $return['msg_test'] = '当前app不是这个用户的';
            echo json_encode($return);exit;
        }
    }


    /**
     * 获取轮播图的信息
     * appid
     */
    public function getLoopImgList(){
        $info = db('loop_img') -> field('content,custom_id') ->  where(['appid' => $this->data['appid']]) -> find();
        if(!$info){
            $return['code'] = 10003;
            $return['msg_test'] = 'appid不正确或者当前用户没有此小程序,或者没有创建轮播图';
            return json($return);
        }else{
            if($info['custom_id'] != $this->custom->id){
                $return['code'] = 10004;
                $return['msg_test'] = '当前的小程序不是这个用户的';
                return json($return);
            }
            $return['code'] = 10000;
            $return['data'] = $info;
            $return['msg_test'] = 'ok';
            return json($return);
        }
    }

    /**
     * 获取所有的商品的id,name
     * appid
     */
    public function getAllShopInfo(){
        $info = db('goods') -> where(['appid' => $this->data['appid']]) -> column('name','id');
        $return['code'] = 10000;
        $return['data'] = $info;
        $return['msg_test'] = 'ok';
        return json($return);
    }

    /**
     * 获取所有的分类的信息
     */
    public function getAllCateInfo(){
        $info = db('goods_cate') -> where(['appid' => $this->data['appid']]) -> column('name','id');
        $return['code'] = 10000;
        $return['data'] = $info;
        $return['msg_test'] = 'ok';
        return json($return);
    }

    /**
     * 获取所有的页面的信息
     */
    public function getAllPageInfo(){
        $data = array(
            'Pages/order/order' => '订单',
            'Pages/User/index' => '我的中心',
        );
        $return['code'] = 10000;
        $return['data'] = $data;
        $return['msg_test'] = 'ok';
        return json($return);
    }

//    /**
//     * 删除数据
//     * appid,loop_id
//     */
//    public function delLoopInfo(){
//        if(!isset($this->data['loop_id'])){
//            $return['code'] = 10002;
//            $return['msg_test'] = '缺少参数值';
//            return json($return);
//        }
//        $res = db('loop_img') -> where(['id' => $this->data['loop_id'] * 1,'custom_id' => $this->custom->id]) -> delete();
//        if($res){
//            $return['code'] = 10000;
//            $return['msg_test'] = 'ok';
//            return json($return);
//        }else{
//            $return['code'] = 10003;
//            $return['msg_test'] = 'appid不对或者loop_id不存在';
//            return json($return);
//        }
//    }

    /**
     * 设置轮播图的，接受前台传递过来的参数
     * appid,info
     */
    public function setLoopImg(){
        if(!isset($this -> data['info'])){
            $return['code'] = 10002;
            $return['msg_test'] = '参数值缺失';
            return json($return);
        }
        $info = $_POST['info'];

        $info = json_decode($info,true);
        if(is_null($info)){
            $return['code'] = 10003;
            $return['msg_test'] = '数据格式不正确';
            return json($return);
        }
        $res = db('loop_img') -> field('id') -> where(['appid' => $this->data['appid']]) -> find();
        if($res){
            $re = db('loop_img') -> where(['id' => $res['id']]) -> setField('content',$_POST['info']);
        }else{
            $loopInfo['content'] = $_POST['info'];
            $loopInfo['appid'] = $this->data['appid'];
            $loopInfo['custom_id'] = $this->custom->id;
            $re = db('loop_img') -> insertGetId($loopInfo);
        }
        if($re){
            $return['code'] = 10000;
            $return['msg_test'] = '成功';
            return json($return);
        }else{
            $return['code'] = 10004;
            $return['msg_test'] = '失败';
            return json($return);
        }

    }

    /**
     * 设置风格
     */
    public function setAppStyle(){
        if(!isset($this->data['style'])||!isset($this->data['value'])){
            $return['code'] = 10001;
            $return['msg_test'] = '请传递参数';
            return json($return);
        }
        switch ($this->data['style']){
            case 'theme':
                $rule = "/^[0-9]{1}$/";
                $field = 'theme';
                break;
            case 'layout':
                $rule = "/^[0-2]{1}$/";
                $field = 'layout';
                break;
            case 'search':
                $rule = "/^[0-1]{1}$/";
                $field = 'search';
                break;
            case 'service':
                $rule = "/^[0-1]{1}$/";
                $field = 'on_service';
                break;
            default:
        }
        if(!isset($rule) || !isset($field)){
            $return['code'] = 10002;
            $return['msg_test'] = '错误456';
            return json($return);
        }
        if(!preg_match($rule,$this -> data['value'])){
            $return['code'] = 10003;
            $return['msg_test'] = '格式不正确';
            return json($return);
        }
        $res = db('app') -> where(['appid' => $this->data['appid']]) -> setField($field,$this->data['value']*1);
        if($res){
            $this -> setAppType();//预留项
            $return['code'] = 10000;
            $return['msg_test'] = '成功';
            return json($return);
        }else{
            $return['code'] = 10004;
            $return['msg_test'] = '失败';
            return json($return);
        }
    }

    /**
     * 获取风格
     */
    public function getAppStyle(){
        if(!isset($this->data['style'])){
            $return['code'] = 10001;
            $return['msg_test'] = '请传递参数';
            return json($return);
        }
        switch ($this->data['style']){
            case 'theme':
                $field = 'theme';
                break;
            case 'layout':
                $field = 'layout';
                break;
            case 'search':
                $field = 'search';
                break;
            case 'service':
                $field = 'on_service';
                break;
            default:
        }
        if(!isset($field)){
            $return['code'] = 10003;
            $return['msg_test'] = '传递错误';
            return json($return);
        }
        $theme = db('app') -> where(['appid' => $this->data['appid']]) -> value($field);
        $return['code'] = 10000;
        $return['data'] = $theme;
        $return['msg_test'] = '成功';
        return json($return);
    }




    private function setAppType(){
        return;
    }


}