<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/9 0009
 * Time: 17:19
 * 后台的关于订单的接口都在这里定义
 */
namespace app\custom\controller;
class Order extends Action{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input("post.",'','htmlspecialchars');
        if(!isset($this->data['appid'])){
            $return['code'] = 10021;
            $return['msg_test'] = '参数值缺失';
            echo json_encode($return);exit;
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10022;
            $return['msg_test'] = 'appid格式不正确';
            echo json_encode($return);exit;
        }
        $custom_id = db('app') -> where("appid",$this->data['appid']) -> value('custom_id');
        if($custom_id != $this->custom->id){
            $return['code'] = 10020;
            $return['msg_test'] = '当前app不是这个用户的';
            echo json_encode($return);exit;
        }
    }

    public function getOrderList(){
        $num = isset($this->data['limit_num']) ? $this->data['limit_num'] : 15;
        $page = isset($this->data['page']) ? $this->data['page'] : 1;
        $state = isset($this->data['state']) ? $this->data['state'] : 1;
        $where = array();
        if(isset($this->data['username'])){
            $where['username'] = $this->data['username'];
        }
        if(isset($this->data['order_sn'])){
            $where['order_sn'] = $this -> data['order_sn'];
        }
        if(isset($this->data['tel'])){
            $where['tel'] = $this->data['tel'];
        }
        if(isset($this->data['starttime']) && isset($this->data['endtime'])){
            $where['create_time'] = ['between',[$this->data['starttime'],$this->data['endtime']]];
        }
        dump($where);
        $data = db('goods_order')
            -> field("id,state,username,prepay_time,price,order_sn")
            -> where(['appid' => $this -> data['appid'],'state' => $state])
            -> where($where)
            -> page($page,$num)
            -> select();
        $return['code'] = 10000;
        $return['data'] = $data;
        $return['msg_test'] = 'ok';
        return json($return);
    }

    /**
     * 获取订单详细的信息
     */
    public function getOrderById(){
        if(!isset($this->data['order_id'])){
            $return['code'] = 10001;
            $return['msg_test'] = '传递订单id,也就是订单列表返回去的id';
            return json($return);
        }
        $info = db('goods_order')
            -> alias('a')
            -> field("a.custom_id,a.username,a.tel,a.mail,a.province,a.city,a.dist,a.address,a.zipcode,a.state,a.order_sn,b.name,b.pic,b.num,b.price,b.spec_value")
            -> join("__GOODS_CART__ b",'FIND_IN_SET(b.id,a.carts)')
            -> where('a.id',$this->data['order_id'])
            -> find();
        if($info['custom_id'] != $this->custom->id){
            $return['code'] = 10002;
            $return['msg_test'] = '当前订单的不是这个用户的';
            return json($return);
        }
        $return['code'] = 10000;
        $return['data'] = $info;
        $return['msg_test'] = 'ok';
        return json($return);
    }





































}