<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/9 0009
 * Time: 17:19
 * 后台的关于订单的接口都在这里定义
 */
namespace app\custom\controller;
class Order extends Action{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input("get.",'','htmlspecialchars');
        if(!isset($this->data['appid'])){
            $return['code'] = 10001;
            $return['msg_test'] = '参数值缺失';
            echo json_encode($return);exit;
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10002;
            $return['msg_test'] = 'appid格式不正确';
            echo json_encode($return);exit;
        }
        $custom_id = db('app') -> where("appid",$this->data['appid']) -> value('custom_id');
        if($custom_id != $this->custom->id){
            $return['code'] = 10020;
            $return['msg_test'] = '当前app不是这个用户的';
            echo json_encode($return);exit;
        }
    }

    public function getOrderList(){
        $num = isset($this->data['limit_num']) ? $this->data['limit_num'] : 15;
        $page = isset($this->data['page']) ? $this->data['page'] : 1;
        $state = isset($this->data['state']) ? $this->data['state'] : 1;
        $data = db('good_order')
            -> where(['appid' => $this -> data['appid'],'state' => $state])
            -> page($page,$num)
            -> select();
        halt($data);
    }

}