<?php
/**
 * Created by PhpStorm.
 * User: 宋妍妍
 * Date: 2017/12/5 0005
 * Time: 09:04
 */

namespace app\custom\controller;
namespace app\custom\controller;

class Price extends Action
{

    /*构造函数*/
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input('post.','','htmlspecialchars');

    }

     /*获取小程序最大可以创建的数量 和小程序的价格*/
    public  function get_app_setting(){

        if(!isset($this->data['type'])){
            $return['code'] = 10003;
            $return['msg'] = '小程序类型丢失';
            $return['msg_test'] = '小程序类型丢失';
            return json($return);
        }

        $user_id = $this -> custom ->id; //用户id

        $user = db('custom')->where(['id'=>$user_id])->find(); //用户信息


         /*代理商的情况*/
        if($user['is_agency_user'] == 1 ){
            $where['type_auto'] = 1 ;
            $where['type_ssh'] = 1 ;
            $where['user_system'] = 1 ;
        }

        /*普通用户是超级管理员下的情况*/
        if($user['is_belong'] == 0 ){
            $where['type_auto'] = 1 ;
            $where['type_ssh'] = 2 ;
            $where['user_system'] = 1 ;
        }

        /*普通用户是代理商的情况下*/
        if($user['is_belong'] == 1 ){
            $where['type_auto'] = 2 ;
            $where['type_ssh'] = 2 ;
            $where['user_system'] = $user['id_agency'];
        }

        $where['type'] = $this->data['type'];

        $info = db('app_setting')->where($where)->find();

        $return['code'] = 10000;
        $return['data'] = $info;
        return json($return);

    }

    /*订单详情*/
    public function get_app_detail(){
        if(!isset($this -> data['appid'])){
            $return['code'] = 10002;
            $return['msg'] = 'appid不存在或者小名字不存在';
            $return['msg_test'] = 'appid不存在或者小名字不存在';
            return json($return);
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10003;
            $return['msg'] = 'appid是一个8位数';
            $return['msg_test'] = 'appid是一个8位数';
            return json($return);
        }
        $is_true = db('app')->field('id,name,type,create_time,try_time,custom_id,use_time') -> where(['appid' => $this -> data['appid']]) -> find();
        if(!$is_true){
            $return['code'] = 10004;
            $return['msg'] = '当前用户没有此小程序,appid不对';
            $return['msg_test'] = '当前用户没有此小程序,appid不对';
            return json($return);
        }
        if($is_true['custom_id'] != $this->custom->id){
            $return['code'] = 10005;
            $return['msg'] = '当前小程序不是这个用户的';
            $return['msg_test'] = '当前小程序不是这个用户的';
            return json($return);
        }
        $type = $is_true['type'];
        if(!isset($type)){
            $return['code'] = 10003;
            $return['msg'] = '小程序类型丢失';
            $return['msg_test'] = '小程序类型丢失';
            return json($return);
        }
        $user_id = $this -> custom ->id; //用户id
        $user = db('custom')->field("is_agency_user,is_belong")->where(['id'=>$user_id])->find(); //用户信息
        /*代理商的情况*/
        if($user['is_agency_user'] == 1 ){
            $where['type_auto'] = 1 ;
            $where['type_ssh'] = 1 ;
            $where['user_system'] = 1 ;
        }
        /*普通用户是超级管理员下的情况*/
        if($user['is_belong'] == 0 ){
            $where['type_auto'] = 1 ;
            $where['type_ssh'] = 2 ;
            $where['user_system'] = 1 ;
        }

        /*普通用户是代理商的情况下*/
        if($user['is_belong'] == 1 ){
            $where['type_auto'] = 2 ;
            $where['type_ssh'] = 2 ;
            $where['user_system'] = $user['id_agency'];
        }

        $where['type'] = $type;

        $info = db('app_setting')->where($where)->find();
        $data['name'] = $is_true['name'];
        $data['price'] = $info['price'];
        $data['zk'] = '';
        $data['over_time'] = date('Y年m月d日', strtotime("+".$info['year_num']."year",$is_true['use_time']));//指定时间戳+1天 2017-01-10 21:10:16
        $data['start_time']  =  date('Y年m月d日',$is_true['create_time']);
        $data['all_money'] = $data['price'] - $data['zk'];

        $return['code'] = 10000;
        $return['data'] = $data;
        return json($return);

    }

     /*获取小程序升级数量套餐信息*/
    public function  get_app_num(){

         $user_id = $this -> custom ->id; //用户id
         $user = db('custom')->where(['id'=>$user_id])->find(); //用户信息
         /*代理商的情况*/
         if($user['is_agency_user'] == 1 ){
             $where['type_auto'] = 1 ;
             $where['type_ssh'] = 1 ;
             $where['user_system'] = 1 ;
         }

         /*普通用户是超级管理员下的情况*/
         if($user['is_belong'] == 0 ){
             $where['type_auto'] = 1 ;
             $where['type_ssh'] = 2 ;
             $where['user_system'] = 1 ;
         }

         /*普通用户是代理商的情况下*/
         if($user['is_belong'] == 1 ){
             $where['type_auto'] = 2 ;
             $where['type_ssh'] = 2 ;
             $where['user_system'] = $user['id_agency'];
         }

         $info = db('app_num')->where($where)->select();

         $return['code'] = 10000;
         $return['data'] = $info;
         return json($return);

     }



}