<?php
/**
 * Created by PhpStorm.
 * User: 宋妍妍
 * Date: 2017/11/14 0014
 * Time: 16:11
 * 酒店小程序的手机端接口
 */

namespace app\custom\controller;
use think\Controller;

class Rooms extends Xiguakeji
{

    /*构造函数*/
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input('post.','','htmlspecialchars');
        if(!isset($this -> data['appid'])){
            $return['code'] = 10002;
            $return['msg'] = 'appid不存在或者预约名字不存在';
            $return['msg_test'] = 'appid不存在或者预约名字不存在';
            return json($return);
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10003;
            $return['msg'] = 'appid是一个8位数';
            $return['msg_test'] = 'appid是一个8位数';
            return json($return);
        }
    }

    /*品牌信息*/
    public  function brands(){
        $where['appid'] = $this->data['appid'];
        $info = db('app')->field('id,site_url,start_time,over_time,address,tel,desc,name,pic')->where($where)->find();

            $return['code'] = 10000;
            $return['data'] = $info ;
            return json($return);

    }

    /*获取门店列表*/
    public function  stores(){

        $page = isset($this -> data['page']) ? $this -> data['page'] : 1;
        $limit = isset($this -> data['number']) ? $this -> data['number'] : 15;
        $stores = db("stores")
            ->where(['appid' => $this -> data['appid'],'state' => 1])
            ->page($page)
            ->limit($limit)
            ->order('id desc')
            ->select();


        foreach($stores as $k=>$v){

            $res = db('rooms')->where(['appid' => $v['appid']])->Min("price"); //最低价格
            $stores[$k]['price'] =$res;
            unset($wheres);

            $wheres[]=['exp',"FIND_IN_SET(".$v['id'].",stores_id)"];
            $wheres['appid'] = $v['appid'];

            $room = db('rooms')->where($wheres)->Sum('number_in'); //剩余房间
            $stores[$k]['number'] = $room;
        }

            $return['code'] = 10000;
            $return['data'] = $stores ;
            return json($return);


    }

    /*获取门店详细信息*/
    public function  stores_detail(){

        $where['appid'] = $this -> data['appid'];
        if(isset($this -> data['id'])){
            $where['id'] = $this -> data['id'];
        }

        $stores = db('stores')->where($where)->find();

            $return['code'] = 10000;
            $return['data'] = $stores ;
            return json($return);


    }

    /*获取门店下的房间*/
    public  function  get_rooms(){
        $where['appid'] = $this -> data['appid'];
        if(isset($this->data['stores_id'])) $where[]=['exp',"FIND_IN_SET(".$this->data['stores_id'].",stores_id)"];
        $rooms = db('rooms')->field('id,photo,price,bed_type,room_type,number_in')->where($where)->select();
        foreach($rooms as $k=>$v){
            $pic = explode(',',$v['photo']);
            $rooms[$k]['photo'] = $pic[0];
            /*获取价格调整信息  调整价格  总价*/
            $rules = db('rooms_rules')
                ->where(['appid'=>$this -> data['appid'] ,'rules_range' => $v['room_type'],'stores_id'=>$this->data['stores_id']])
                ->where('start_time','<',time())
                ->where('over_time','>',time())
                ->whereOr(['rules_range'=>'所有房型'])
                ->find();

            if($rules) {
                if ($rules['rules'] == 1) {
                    $rooms[$k]['price'] = $v['price'] * $rules['rules_detail'] + $v['price'];
                } elseif ($rules['rules'] == 2) {
                    $rooms[$k]['price'] = $v['price'] + $rules['rules_detail'];
                } elseif ($rules['rules'] == 3) {
                    $rooms[$k]['price'] = $v['price'] - $v['price'] * $rules['rules_detail'];
                }

            }

        }
            $return['code'] = 10000;
            $return['data'] = $rooms ;
            return json($return);
    }

    /*获取房间详细信息*/
    public  function get_rooms_detail(){
        $where['appid'] = $this -> data['appid'];
        $where['id'] = $this -> data['id'];
        $rooms = db('rooms')->where($where)->find();
        $rooms['photo'] = explode(',',$rooms['photo']);
        /*获取价格调整信息  调整价格  总价*/
        $rules = db('rooms_rules')
            ->where(['appid'=>$this -> data['appid'] ,'rules_range' => $rooms['room_type'],'stores_id'=>$this->data['stores_id']])
            ->where('start_time','<',time())
            ->where('over_time','>',time())
            ->whereOr(['rules_range'=>'所有房型'])
            ->find();

            if($rules){
                if($rules['rules'] == 1 ){
                    $rooms['price'] = $rooms['price']*$rules['rules_detail'] + $rooms['price'];
                }elseif($rules['rules'] == 2){
                    $rooms['price'] = $rooms['price'] + $rules['rules_detail'] ;
                }elseif($rules['rules'] == 3){
                    $rooms['price'] = $rooms['price'] - $rooms['price']*$rules['rules_detail'];
                }
            }

        $rules['start_time'] = date("Y-m-d H:i:s",$rules['start_time']);

        $return['code'] = 10000;
        $return['data'] = $rooms ;
        return json($return);

    }

    /*酒店风格内容获取*/
    public function style_detail(){

        $where['appid'] = $this->data['appid'];
        $info = db('stores_style')->where($where)->find();

        $mystring = $info['pic'];
        $findme   = 'Uploads';
        $pos = strpos($mystring, $findme);

        if(!$pos){
            $info['pic'] = 'Uploads/banner/'.$info['pic'];
        }
        if($pos != 0){
            $info['pic'] = 'Uploads/banner/'.$info['pic'];
        }

        $return['assss'] = $pos ;
        $return['code'] = 10000;
        $return['data'] = $info ;
        return json($return);
    }

    /*生成酒店预约订单*/
    public  function create_order(){


        if(!isset($this -> data['start_time'])  || !isset($this -> data['end_time'])  || !isset($this -> data['username'])  || !isset($this -> data['user_tel'])){
            $return['code'] = 10007;
            $return['msg'] = '参数丢失';
            $return['msg_test'] = '参数丢失';
            return json($return);
        }
        if(!isset($this -> data['stores_id']) || !isset($this -> data['rooms_id'])){
            $return['code'] = 10008;
            $return['msg'] = '门店id或者房间id丢失';
            $return['msg_test'] = '门店id或者房间id丢失';
            return json($return);
        }


       $time = time();
       $order_sn = date('Y').$time.rand(1000,9999);

       $info = db("rooms")->field("room_type,price,bed_type,number_in")->where(['id' => $this->data['rooms_id']])->find();
       $name =$info['room_type'];

       if($info['number_in'] <= 0){
           $return['code'] = 10008;
           $return['msg'] = '房间已满';
           $return['msg_test'] = '房间已满';
           return json($return);
       }

       $address = db("stores")->field('stores_address')->where(['id' => $this->data['stores_id']])->find();

       /*获取价格调整信息  调整价格  总价*/
        $rules = db('rooms_rules')
            ->where(['appid'=>$this -> data['appid'] ,'rules_range' => $info['room_type'],'stores_id'=>$this->data['stores_id']])
            ->where('start_time','<',time())
            ->where('over_time','>',time())
            ->whereOr(['rules_range'=>'所有房型'])
            ->find();
        if($rules){
            if($rules['rules'] == 1 ){
                $info['price'] = $info['price']*$rules['rules_detail'] + $info['price'];
            }elseif($rules['rules'] == 2){
                $info['price'] = $info['price'] + $rules['rules_detail'] ;
            }elseif($rules['rules'] == 3){
                $info['price'] = $info['price'] - $info['price']*$rules['rules_detail'];
            }
        }
        $is_wallet = $this->data['is_wallet'];
        $data = $this->data;
        $data['price'] = $info['price'];
        $data['total_price'] = $this->data['num'] * $data['price'];
        $data['user_id'] = $this->user['id'];
        $data['order_sn'] = $order_sn;
        $data['create_time'] = $time;
        $data['openid'] = $this->user['openid'];
        $data['room_type'] = $info['room_type'];
        $data['bed_type'] =$info['bed_type'];
        $data['address'] =$address['stores_address'];
        $data['end_time'] =strtotime($this->data['end_time']." 14:00");
        $data['start_time'] =strtotime($this->data['start_time']." 12:00");

        $total_fee = $this->data['num'] * $data['price'];
        unset($data['session_key']);
        unset($data['apps']);
        unset($data['is_wallet']);

        $id = db('rooms_order')->insertGetId($data);

        $weapp = new \app\weixin\controller\Common($this->data['appid']);
        $order_id = $id;
        $attach = json_encode(['type'=>3,'id'=>$order_id]);//type值为3时，是酒店小程序的支付请求
        //再生成订单之前，判断用户是否要使用余额支付，如果支付，判断订单的金额减去用户的余额是否为0，如果为0不生成prepay_id，并把用户余额减去订单金额，如果不为0，说明订单金额多。
        $orderInfo = array();
        if(isset($is_wallet) &&  $is_wallet == 1){
            //用户想要使用余额，判断是否有余额，并判断是订单金额多还是余额金额多
            $userInfo = db('user') -> field('money') -> where(['id' => $this -> user['id']]) -> find();
            if($userInfo['money'] > 0){
                //判断订单金额多还是余额多，两种情况不一样
                if($total_fee > $userInfo['money']){
                    //订单金额多，把订单金额减去用户余额，同时，把用户余额值为0，把订单表中的user_money变为用户余额，表示当前订单使用了这么多金额。
                    $orderInfo['total_fee'] = $total_fee - $userInfo['money'];
                    $total_fee = $total_fee - $userInfo['money'];
                    $orderInfo['user_money'] = $userInfo['money'];
                    db('user') -> where(['id' => $this -> user['id']]) -> setField('money',0);
                }else{
                    //用户的余额大于订单的金额，订单金额值为0，user_money是订单金额，用户余额变为余额-订单金额
                    $orderInfo['total_fee'] = 0;
                    $orderInfo['user_money'] = $total_fee;
                    db('user') -> where(['id' => $this -> user['id']]) -> setDec('money',$total_fee);
                    $total_fee = 0;
                }

            }else{
                //用户没有余额，或余额不正确,不处理，直接生成prepay_id
            }
        }else{
            $orderInfo['total_fee'] = $total_fee ;
        }

        if($total_fee == 0){
            //用户余额大于订单金额
            $prepay_id = $this -> user['id'] . time() . mt_rand(1000,9999);
        }else{
            $prepay_id = $weapp -> get_prepay_id($this->user['openid'],$total_fee*100,$order_sn,$attach,'西瓜科技-'.$name);
            if(!$prepay_id){
                $return['code'] = 10005;$return['msg'] = '微信小程序参数配置有误';return json($return);
            }
        }

        $orderInfo['prepay_id'] = $prepay_id;
        $orderInfo['prepay_time'] = time();

        db('rooms_order') ->where(['id'=>$order_id])->update($orderInfo);
        $return['code'] = 10000;
        $return['data']  = ['id'=>$order_id];
        $return['msg_test'] = '可以向付款页跳转了';
        return json($return);

    }

    /*订单详情页*/
    public function get_order_detail(){

        $where['id'] = $this->data['id'];
        $where['appid'] = $this->data['appid'];
        $where['user_id'] = $this->user['id'];
        $info = model('rooms_order')->where($where)->find();
        $return['code'] = 10000;
        $return['data'] = $info;
        return json($return);


    }

    //付款页核对订单，调起支付
    function pay(){

        if(!isset($this->data['id'])){
            $return['code'] = 10001;$return['msg_test'] = '缺少参数id';return json($return);
        }
        $order = db('rooms_order') -> where('id',$this->data['id']) -> find();
        $num = db('rooms') ->field('number_in')-> where('id',$order['rooms_id']) -> find();
  
        if($num['number_in'] <= 0){
            $return['code'] = 10008;
            $return['msg'] = '房间已满';
            $return['msg_test'] = '房间已满';
            return json($return);
        }
        if(empty($order) || $order['appid'] != $this->apps  || $order['user_id'] != $this->user['id'] ){
            $return['code'] = 10001;$return['msg_test'] = '订单不存在';return json($return);
        }
        if($order['state'] != 0 ){
            $return['code'] = 10001;$return['msg_test'] = '订单不是待付款状态';return json($return);
        }
  
        //判断当前订单是否过期，从创建起，两小时之内
        $time = time() - 7200;
        if($order['create_time'] < $time){

            $return['code'] = 10011;

            $return['msg'] = '订单已过期';return json($return);
        }
        $weapp = new \app\weixin\controller\Common($this->apps);
        //prepay_id是否过期，过期重新生成
        if( time() - $order['prepay_time'] > 7200 ){
            $order_sn = date('Y').time().rand(1000,9999);
            $prepay_id = $weapp ->get_prepay_id($this->user['openid'],$order['total_price']*100,$order['order_sn'],$order['id'],'西瓜科技-'.$order['room_type']);

            if(!$prepay_id){
                $return['code'] = 10010;
                $return['msg_test'] = '生成prepay_id出错';
            }
            model('rooms_order') -> save(['prepay_id'=>$prepay_id,'prepay_time'=>time(),'order_sn' => $order_sn],['id'=>$order['id']]);
        }else{
            $prepay_id = $order['prepay_id'];
        }

        $return['code'] = 10000;
        $return['msg_test'] = 'data内数据即调起支付所需参数，无需进行加密操作，直接使用';
        $return['data'] =$weapp -> paysign($prepay_id);
        return json($return);
    }

    //@return \think\response\Json
    //当用户的订单价格是0的时候,不需要调用微信的接口，直接修改订单状态
    public function setUserOrderState(){
        $order_id = $this -> data['id'];
        if(!isset($order_id) && !$order_id){
            $return['code'] = 10001;
            $return['msg_test'] = '订单id不对';
            return json($return);
        }
        $orderInfo = db('rooms_order') -> field('user_id,appid,username,total_price,user_money,state,total_fee') -> where(['id' => $order_id]) -> find();
        if(!$orderInfo || $orderInfo['user_id'] != $this -> user['id'] || $orderInfo['total_fee'] > 0 || $orderInfo['user_money'] == 0 || $orderInfo['state'] != 0){
            $return['code'] = 10002;
            $return['msg_test'] = '参数错误';
            return json($return);
        }
        //修改订单的状态，并发送邮件给管理员，这种订单不参与分销
        model('rooms_order') -> save(['state'=>1],['id'=>$order_id]);
        //判断当前小程序是否有分销
        action('custom/Notify/sendMail',[$orderInfo['appid'],$orderInfo['username']]);
        $return['code'] = 10000;
        $return['msg_test'] = '支付成功';
        return json($return);
    }

    //订单列表，未付款，已付款，已确定，退款中,已退款
    public  function order_list(){
        if( !isset($this->data['type']) || !in_array($this->data['type'], [0,1,2]) ){
            $return['code'] = 10001;$return['msg_test'] = '缺少订单类型type';return json($return);
        }
        $page = isset($this->data['page']) ? $this->data['page'] : 1 ;
        $limit_num = isset($this->data['limit_num']) ? $this->data['limit_num'] : 10 ;
        $where['user_id'] = $this->user['id'];
        $where['state'] = $this->data['type'];
        $where['appid'] = $this->data['appid'];
        $where['is_delete'] = 0;

        //->alias('a')->join($join)  -> where($where)
         /*已确认的订单下  包含 已支付 已入住 退款中的 订单 */
        if($this->data['type'] == 1){
            $info = db('rooms_order')
                -> where($where)
                ->whereOr('state','3')
                ->whereOr('state','4')
                ->whereOr('state','5')
                -> page($page)
                -> limit($limit_num)
                -> order('id desc')
                -> select();
        }else{
            $info = db('rooms_order')
                -> where($where)
                -> page($page)
                -> limit($limit_num)
                -> order('id desc')
                -> select();
        }


        foreach($info as $k=>$v){
            $rooms = db('rooms')->field('id,photo')->where(['id' => $v['rooms_id']])->find();
            $pic = explode(',',$rooms['photo']);
            $info[$k]['room_photo'] = $pic[0];
        }


        $return['code'] = 10000;
        $return['msg_test'] = '加载成功';
        $return['data'] = $info;
        return json($return);

    }

    /*订单详情  appid  id*/
    public  function  get_order(){

       $where['appid'] = $this->data['appid'];
       $where['user_id'] = $this->user['id'];
       $where['id'] = $this->data['id'];

       $info = db('rooms_order')->where($where)->find();

       $rooms = db('rooms')->field('id,photo')->where(['id' => $info['rooms_id']])->find();
       $pic = explode(',',$rooms['photo']);
       $info['room_photo'] = $pic[0];
       $return['code'] = 10000;
       $return['data'] = $info;
       return json($return);
<<<<<<< HEAD
=======

>>>>>>> f3c10d5320de806fe333c38aaa4b99cf1c479c03
   }

    /*退款申请*/
    public  function  refunds(){

       $where['appid'] = $this->data['appid'];
       $where['id'] = $this->data['id'];
       $where['user_id'] = $this->user['id'];
       $check  = db('rooms_order')->field("id,state,start_time,rooms_id")->where($where)->find();
        if($check['state'] != 1 ){
            $return['code'] = 10004;
            $return['msg'] = '该订单不支持退款';
            return json($return);
        }
        $time = $check['start_time'] + 60*60*18;

        if(time() > $time){
            $return['code'] = 10004;
            $return['msg'] = '18:00之后不允许退款';
            return json($return);
        }
        if(time() > $check['end_time']){
            $return['code'] = 10004;
            $return['msg'] = '该订单不支持退款';
            return json($return);
        }

        $data['state'] = 4;
        $data['refund_msg'] = $this->data['refund_msg'];

        db('rooms')-> where(['id' => $check['rooms_id']])->setInc('number_in' , 1);//申请退款房间剩余数量加上
        $res = db('rooms_order')->where($where)->update($data);
        if($res){
           $return['code'] = 10000;
           $return['msg'] = '申请退款成功';
           $return['msg_test'] = '申请退款成功';
           return json($return);
       }else{
           $return['code'] = 10001;
           $return['msg'] = '网络错误';
           $return['msg_test'] = '网络错误';
           return json($return);
       }

    }

    //获取更多信息
    function info(){
        $info['user'] = $this->user->nickName;
        $info['avatarUrl'] = $this->user->avatarUrl;
        $info['money'] = $this->user->money;
        $return['code'] = 10000;
        $return['data'] = $info;
        return json($return);
    }
    
    /*取消订单*/
    public function close_order(){

        $where['appid'] = $this->data['appid'];
        $where['id'] = $this->data['id'];

        $order = db('rooms_order')->where($where)->find();
        if(isset($order['user_money']) && $order['user_money'] > 0){
            db('user') -> where(['id' => $this -> user['id']]) -> setDec('money',$order['user_money']);
        }
        $res = db('rooms_order')->where($where)->update(["is_delete" => 1 ]);
        if($res){
            $return['code'] = 10000;
            $return['msg'] = '取消成功';
            return json($return);
        }else{
            $return['code'] = 10001;
            $return['msg'] = '取消失败';
            return json($return);
        }

    }


}