<?php
/*
 * 提现记录
 */
namespace app\custom\controller;

class Withdraw extends Action{
    
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this -> data = input('post.','','htmlspecialchars');
        if(!isset($this->data['appid'])){
            $return['code'] = 10100;
            $return['msg_test'] = 'appid参数值缺失';
            echo json_encode($return);exit;
        }
        if(!preg_match("/^\d{8}$/",$this -> data['appid'])){
            $return['code'] = 10200;
            $return['msg_test'] = 'appid格式不正确';
            echo json_encode($return);exit;
        }
        $custom_id = db('app') -> where(['appid' => $this->data['appid']]) -> value('custom_id');
        if($custom_id != $this->custom->id){
            $return['code'] = 10300;
            $return['msg_test'] = '当前app不是这个用户的';
            echo json_encode($return);exit;
        }
    }
    
    public function withdraw_list(){
        $page = isset($this->data['page']) ? $this->data['page'] : 1;
        $limit_num = isset($this->data['limit_num']) ? $this->data['limit_num'] : 10;
        $withdraw_data = array();
        $withdraw_data['appid'] = $this->data['appid'];
        if(isset($this->data['starttime']) && isset($this->data['endtime'])){
            if($this->data['starttime'] && $this->data['endtime']){
                $where['create_time'] = ['between',[$this->data['starttime'],$this->data['endtime']]];
            }
        }
        if (isset($this->data['is_audit'])) {
            if ($this->data['is_audit']) {
                $withdraw_data['is_audit'] = $this->data['is_audit'];
            }
        }
        if (isset($this->data['withdraw_type'])) {
            if ($this->data['withdraw_type']) {
                $withdraw_data['withdraw_type'] = $this->data['withdraw_type'];
            }
        }
        if (isset($this->data['tel'])) {
            if ($this->data['tel']) {
                $withdraw_data['tel'] = $this->data['tel'];
            }
        }
        if (isset($this->data['name'])) {
            if ($this->data['name']) {
                $withdraw_data['name'] = $this->data['name'];
            }
        }
        $data = db('withdraw_record')
                ->field('id,appid,name,tel,money,withdraw_type,ali_number,bank_name,bank_number,is_audit,create_time,success_time')
                ->where($withdraw_data)
                ->order('id desc')
                ->page($page,$limit_num)
                ->select();
        $return['code'] = 10000;
        $return['msg_test'] = '查询成功';
        $return['data'] = $data;
        return json($return);
    }
}